# namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
--- 
# web-server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-server
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: web
        # Nginx image that responds to HTTP on port 80
        image: nginx:latest
        ports:
        - containerPort: 80

---
# web-server-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
  namespace: test
spec:
  selector:
    app: simple-web
  type: LoadBalancer            # internal cluster endpoint
  ports:
  - protocol: TCP
    port: 80                # port clients use inside the cluster
    targetPort: 80          # port the container listens on
