apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-address-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.2.15-192.168.2.20 # 192.168.2.15-192.168.2.20
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: primary-advertisement
  namespace: metallb-system
