user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 4096;
    # multi_accept on;
}

http {

    ##
    # Basic Settings
    ##

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 15;
    types_hash_max_size 2048;
    # server_tokens off;

    # server_names_hash_bucket_size 64;
    # server_name_in_redirect off;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ##
    # SSL Settings
    ##

    ssl_protocols TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
    ssl_prefer_server_ciphers off;

    ##
    # Logging Settings
    ##

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    ##

    gzip on;

    # gzip_vary on;
    # gzip_proxied any;
    # gzip_comp_level 6;
    # gzip_buffers 16 8k;
    # gzip_http_version 1.1;
    # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    ##
    # Virtual Host Configs
    ##

    include /etc/nginx/conf.d/*.conf;
    #include /etc/nginx/sites-enabled/*;
    #include /etc/nginx/sites-enabled/*;

    server {
        # Enable HTTP/2 for HTTPS connections
        listen 443 ssl http2;
        
        # SSL certificate configurations (ensure you have your SSL certificates configured)
        ssl_certificate /etc/nginx/ssl/nginx.crt;  # Your certificate path
        ssl_certificate_key /etc/nginx/ssl/nginx.key;  # Your key path

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Define proxy locations
        location /prometheus/ {
            proxy_pass http://192.168.88.242:9090;
        }

        location /home-server/ {
            proxy_pass http://192.168.88.242:5000;
        }
    }

    # Ensure to have a redirect for HTTP to HTTPS if desired
    server {
        listen 80;
        server_name yourdomain.com;
        return 301 https://$host$request_uri;
    }
}
