# Default values: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

crds:
  keep: false

server:
  # Disable TLS termination in the server for home lab (plain HTTP on the LAN)
  extraArgs:
    - --insecure
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.2.22

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
        prometheus.io/path: "/metrics"

repoServer:
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"
        prometheus.io/path: "/metrics"

applicationSet:
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/metrics"
